// Generated by CoffeeScript 1.7.1
(function() {
  var match, v;

  match = function(regex, val, msg, cb) {
    if (regex.test(val)) {
      return (typeof cb === "function" ? cb() : void 0) || true;
    }
    return (typeof cb === "function" ? cb(msg) : void 0) || false;
  };

  module.exports = v = {
    emailSync: function(email) {
      var regex;
      regex = /^"?[A-Z0-9_%+-]+\.?[A-Z0-9_%+-]*"?[^\.]@\[?([^-_]([A-Z-_]+\.[A-Z]+)+|[0-9]{3}\.[0-9]{3}\.[0-9]{3}\.[0-9]{3})\]?$/i;
      return match(regex, email);
    },
    email: function(msg) {
      if (msg == null) {
        msg = "Invalid Email specified";
      }
      return function(email, cb) {
        if (!v.emailSync(email)) {
          return cb(msg);
        }
        return cb();
      };
    },
    urlSync: function(url, opts) {
      var privateAndLocalNetworks, regexStr;
      if (opts == null) {
        opts = {};
      }
      privateAndLocalNetworks = function() {
        if (opts.allowPrivateNetworks) {
          return '';
        }
        return "(?!10(?:\\.\\d{1,3}){3})" + "(?!127(?:\\.\\d{1,3}){3})" + "(?!169\\.254(?:\\.\\d{1,3}){2})" + "(?!192\\.168(?:\\.\\d{1,3}){2})" + "(?!172\\.(?:1[6-9]|2\\d|3[0-1])(?:\\.\\d{1,3}){2})";
      };
      regexStr = "^" + "(?:(?:https?|ftp)://)" + "(?:\\S+(?::\\S*)?@)?" + "(?:" + privateAndLocalNetworks() + "(?:[1-9]\\d?|1\\d\\d|2[01]\\d|22[0-3])" + "(?:\\.(?:1?\\d{1,2}|2[0-4]\\d|25[0-5])){2}" + "(?:\\.(?:[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-4]))" + "|" + "(?:(?:[a-z\\u00a1-\\uffff0-9]+-?)*[a-z\\u00a1-\\uffff0-9]+)" + "(?:\\.(?:[a-z\\u00a1-\\uffff0-9]+-?)*[a-z\\u00a1-\\uffff0-9]+)*" + "(?:\\.(?:[a-z\\u00a1-\\uffff]{2,}))" + ")" + "(?::\\d{2,5})?" + "(?:/[^\\s]*)?" + "$";
      return match(new RegExp(regexStr, "i"), url);
    },
    url: function(msg, opts) {
      if (msg == null) {
        msg = "Invalid Url specified";
      }
      return function(url, cb) {
        if (!v.urlSync(url, opts)) {
          return cb(msg);
        }
        return cb();
      };
    }
  };

}).call(this);
