// Generated by CoffeeScript 1.7.1
(function() {
  var v;

  module.exports = v = {
    JSONSync: function(json) {
      var e;
      try {
        JSON.parse(json);
        return true;
      } catch (_error) {
        e = _error;
        return false;
      }
    },
    JSON: function(msg) {
      if (msg == null) {
        msg = "Invalid JSON string specified";
      }
      return function(json, cb) {
        if (!v.JSONSync(json)) {
          return cb(msg);
        }
        return cb();
      };
    }
  };

}).call(this);
